name: Windows Test Results
on:
  workflow_run:
    workflows: [Windows Build ğŸŸ¥ğŸŸ©ğŸŸ¦ğŸŸ¨, Linux Build ğŸ§, MacOSX Build ğŸ]
    types: [ completed ]

permissions:
    checks: write

jobs:
  checks:
    runs-on: ${{matrix.config.runos}}
    strategy:
        fail-fast: false
        matrix:
          config:
          - {
                name: "Windows Test Results",
                runos: windows-latest,
                artifact-name: "torque3dLinuxGCCUnitTest"
            }
          - {
              name: "Ubuntu Test Results",
              artifact-name: "torque3dLinuxGCCUnitTest"
            }
          - {
                name: "Mac Test Results",
                artifact-name: "torque3dMacOSXCLANGUnitTest"
            }
    steps:
      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
        with:
          artifact-name: ${{matrix.config.artifact-name}}
          name: ${{matrix.config.name}}

